language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: fqZVMR9cPuXyfg7Pk/RtChFhWd8xVjwmz5/c6vS6bkKGLUn1Yh0evW3Vlj9erx2XwkxVNWNiZm7wmL/tpJEkCmQ+j31TFTS/w1uqQsrqL07HsI7rCl9Yc+CuVvvdihFti+h7AGkVGVtXk+jzHaOiUQl5jZPEVroTYW1Qn0darlHRxmpgeW8hJtdSELH3ACxGsw18l2CKWlGJ+WatRzyrq82OIfSN5nl9EpxCaZBrw5g5wqZcyniOfS8oApX3esfdejk6tUvsmH0j4VScmXd0xP3kN6VQWJl+cyyYXsYHV2+HsAz+BRvhOLYxbj+O/GFr8iIS2s05orhGo3eu2/v5VYIIJiIDFF/QBuR3p3WeOKiZa25CsHu6I2e5qDzVk8VtJXlChAdu4qbEsWLwqXp8E92s8KJZ1YMz7HFuQiB1vXVQGQcFzIse9PSBX4ynTXPz40rckholz986Ap5VmaVYAnIjNKTLHY89bLaLMppHYiNAdcqlZdqw0+tJpsjN6IZuKHxf5fhMmKSrwKebj+My1lEdjW1ZVQY48P2225WHpqOTsCuldGtLn6KarLRX05b3e10IpXgX6mfCAMzaNhooaRZXuwS1oPdOtsTmdPBzqrlwMi/5FT/Njy+D1lg1HX1ucHaLOyqsheafUaSVH1CYn9PQFArZ4LGsyTzElq3qJ7U=
app: jkw-rancid-tomatillos-deploy
skip_cleanup: true